### ISSUE TITLE
v2019 release roadmap

### ISSUE THREAD

**Issue by krassowski** [reimandlab/ActiveDriverDB#159]
- [x] prepare changelog
- [x] calculate and import ActveDriver lists
- [x] consider collapsing glycosites subtypes in filters
- [x] copy the logo graphics for glycosylation motifs to the production server
- [x] export data for download and update the download files
- [x] add the changelog to the website

**Comment by krassowski** [comment]
# (Draft) changelog notes
I will keep updating the notes below

## PTM sites
- Glycosylation sites (N-, O-, S-, C-) were added based on the UniProt (May 2019)
- Other types of PTM sites were updated using the UniProt data
- The origin database is now stored and displayed for each PTM site to help users in further investigation, including scrutinizing the evidence quality and citing the original reporters. It can be accessed by hovering over the site in the SequenceView:
   ![ptm_site_source](https://user-images.githubusercontent.com/5832902/76145260-025dbf00-6080-11ea-9757-d155e6e97189.png)

## Mutations

### Inherited/Clinical/ClinVar

- Clinical mutations from ClinVar were updated using May 2019 release (20190520)
- ClinVar mutations are now stringently filtered to only include clinically relevant, non-somatic mutations. Specifically:
   - mutations with germline, parental, maternal, biparental, etc origin are included; de novo mutations are also included
  - mutations with a somatic origin, or missing the origin information are excluded (see [here](https://github.com/reimandlab/ActiveDriverDB/blob/436553dafca413f5d74a9d21f3bb22bdd07c3ec3/website/imports/mutations/clinvar.py#L349-L356) for the blacklist)
  - only mutations associated with a disease, or conferring sensitivity (but not resistance) are included (details [here](https://github.com/reimandlab/ActiveDriverDB/blob/436553dafca413f5d74a9d21f3bb22bdd07c3ec3/website/imports/mutations/clinvar.py#L142-L147))

- ClinVar mutations include more metadata:
  - gold stars which describe the quality of evidence are now displayed (one per underlying variation)
  - links to both the dbSNP entry (e.g. https://www.ncbi.nlm.nih.gov/snp/rs755131800) and the variation entries in ClinVar database (VCV record, e.g. https://www.ncbi.nlm.nih.gov/clinvar/variation/548576/) are now provided
   ![clinvar_annotations](https://user-images.githubusercontent.com/5832902/76145356-af383c00-6080-11ea-9607-efc632565f9f.png)

## Genes
Gene information, including identifiers mapping to external databases were updated using the UCSC Genome Browser distributed tables of RefSeq database and the UniProt database.

## Sequence view
- conservation track showing phyloP scores (based on the 100way track from UCSC Genome Browser) was added. The per-aminoacid scores were calculated as an average of the codon scores.

## Pathways
- Reactome and Gene Ontology pathways were updated using the gprofiler distributed lists
- top pathways were calculated ActivePathways

**Comment by krassowski** [comment]
- [ ] change URLs on v2017 download page
- [ ] add '17 to v2017 logo
